[package]
name = "hello_world_bin"
version = "0.1.0"
authors = ["Peter Kolloch <info@eigenvalue.net>"]
edition = "2018"

[dependencies]

[target.'cfg(never_happens)'.dependencies]
cfg-if = "1"

[target.'cfg(doesnt_exist = "should pass")'.dependencies]
cfg-if = "1"
